### ISSUE TITLE
data/...._TML files not included in github, but needed for running CATENA

### ISSUE THREAD

**Issue by mfeblowitz** [paramitamirza/CATENA#2]
There are a few places in the code that rely on the presence of TML data files. Yet all of the *_TML directories and files have been gitignored:

    /Catena-train_TML/
    /Causal-TimeBank_TML/
    /TempEval3-eval_TML/
    /TempEval3-train_TML/

Here is one manifestation:

```
Train CATENA temporal and causal models...
Exception in thread "main" java.io.FileNotFoundException: /homes/hny2/mfeb/causal/CATENA_project/CATENA/./data/Catena-train_TML/ABC19980108.1830.0711.tml (No such file or directory)
```

Can these please be added back, please? I'd like to work with TML files if that's possible.

**Comment by mfeblowitz** [comment]
Ok - found the data in an older version.

**Comment by ghost** [comment]
@mfeblowitz where did you find the data/...._TML files?

**Comment by eecrazy** [comment]
@abhi089 I think you can find it here https://github.com/paramitamirza/CATENA/tree/7e35a4d53f4a397be8524a0c995fac9df6e37ba0

**Comment by ghost** [comment]
@eecrazy Thank you!
